# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [119]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [120]:
# your code here
np.version.version

'1.24.3'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [121]:
# Method 1
a = np.random.random((2, 3, 5))

In [122]:
# Method 2
a = np.random.randint(0, 100, (2, 3, 5))

In [123]:
# Method 3
a = np.random.normal(0, 1, (2, 3, 5))

#### 4. Print *a*.


In [124]:
# your code here
a

array([[[-0.03599202, -0.21664129, -1.9846994 ,  1.37986368,
          0.05188555],
        [-1.55392675, -0.00377847, -0.6836382 , -0.28554009,
         -0.80804475],
        [-0.67727694, -1.82000808, -0.67689994, -0.04586065,
          0.64319998]],

       [[-0.25092098,  1.23453628,  0.96889284,  0.5323848 ,
          0.31859062],
        [-1.03855199, -1.40333484, -0.66756252, -0.6193398 ,
          2.43354419],
        [-1.09039082, -0.04749433,  1.7110255 ,  0.21527788,
         -0.7681353 ]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [125]:
# your code here
#Create a 5x2x3 3-dimensional array with all values equaling 1.
b = np.ones((5, 2, 3))

#### 6. Print *b*.


In [126]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [127]:
# your code here
len(a) == len(b)

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [128]:
# your answer here
a + b # ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [129]:
# your code here
c = np.reshape(b, (2, 3, 5))
c


array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [130]:
# your code/answer here
d = a + c # a and c have the same shape

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [131]:
# your code/answer here
print(a)
print(d)
# Each cell is 1 + d

[[[-0.03599202 -0.21664129 -1.9846994   1.37986368  0.05188555]
  [-1.55392675 -0.00377847 -0.6836382  -0.28554009 -0.80804475]
  [-0.67727694 -1.82000808 -0.67689994 -0.04586065  0.64319998]]

 [[-0.25092098  1.23453628  0.96889284  0.5323848   0.31859062]
  [-1.03855199 -1.40333484 -0.66756252 -0.6193398   2.43354419]
  [-1.09039082 -0.04749433  1.7110255   0.21527788 -0.7681353 ]]]
[[[ 0.96400798  0.78335871 -0.9846994   2.37986368  1.05188555]
  [-0.55392675  0.99622153  0.3163618   0.71445991  0.19195525]
  [ 0.32272306 -0.82000808  0.32310006  0.95413935  1.64319998]]

 [[ 0.74907902  2.23453628  1.96889284  1.5323848   1.31859062]
  [-0.03855199 -0.40333484  0.33243748  0.3806602   3.43354419]
  [-0.09039082  0.95250567  2.7110255   1.21527788  0.2318647 ]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [132]:
# your code here
e = a * c
e

array([[[-0.03599202, -0.21664129, -1.9846994 ,  1.37986368,
          0.05188555],
        [-1.55392675, -0.00377847, -0.6836382 , -0.28554009,
         -0.80804475],
        [-0.67727694, -1.82000808, -0.67689994, -0.04586065,
          0.64319998]],

       [[-0.25092098,  1.23453628,  0.96889284,  0.5323848 ,
          0.31859062],
        [-1.03855199, -1.40333484, -0.66756252, -0.6193398 ,
          2.43354419],
        [-1.09039082, -0.04749433,  1.7110255 ,  0.21527788,
         -0.7681353 ]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here
# e is equal to c because 1 * x = x

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [133]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [134]:
# your code here
f = np.empty((2, 3, 5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [192]:
# your code here
def label_arr(inpt, labels):
    np_input = np.array(inpt)
    output = list(np.empty(np_input.shape, dtype=str))
    k_max = np.max(d)
    k_min = np.min(d)
    k_mean = np.mean(d)
    for index1, i in enumerate(np_input):
        for index2, j in enumerate(i):
            for index3, k in enumerate(j):
                if k == k_min:
                    output[index1][index2][index3] = labels[0]
                elif k > k_min and k < k_mean:
                    output[index1][index2][index3] = labels[1]
                elif k == k_mean:
                    output[index1][index2][index3] = labels[2]
                elif k > k_mean and k < k_max:
                    output[index1][index2][index3] = labels[3]
                elif k == d_max:
                    output[index1][index2][index3] = labels[4]
    return output

rng = list(range(0, 101, 25))
f = label_arr(d, rng)

f

[array([['7', '7', '7', '2', '7'],
        ['7', '7', '2', '2', '2'],
        ['7', '2', '7', '7', '7']], dtype='<U1'),
 array([['2', '2', '2', '2', ''],
        ['7', '7', '7', '7', '7'],
        ['2', '7', '0', '7', '7']], dtype='<U1')]

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [139]:
# your code here
d = [[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
label_arr(d, rng)

array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [193]:
# your code here
label_arr(d, ['A', 'B', 'C', 'D', 'E'])

[array([['D', 'D', 'D', 'B', 'D'],
        ['D', 'D', 'B', 'B', 'B'],
        ['D', 'B', 'D', 'D', 'D']], dtype='<U1'),
 array([['B', 'B', 'B', 'B', ''],
        ['D', 'D', 'D', 'D', 'D'],
        ['B', 'D', 'A', 'D', 'D']], dtype='<U1')]